<?php
/**
 * Auto-generated by automark-astro-main build:main — do not edit manually.
 */
$themeStylesheets = [
    '/_astro/Base.g5aUpptx.css',
];
$themeScripts = [
    '/scripts/main.js',
    '/scripts/animations.js',
];
